feat: 맛집 상세정보 조회 api 추가
7th-wanted-pre-onboarding-teamN/tasty-spots-finder pull request #10
Opened 2023-11-02 14:02 UTC by junkyu92

### 작업 내용
- 맛집 상세정보 조회 api 추가

### 변경 사항(추가시엔 추가사항)
- fetch조인 쿼리 한번으로 맛집정보 + 리뷰리스트 + 리뷰작성자 정보 조회
- DTO로 Projection하는 과정에 response에 필요한 내용만 반환 (ex. password 반환 X)

### 특이 사항
- 서비스에 로직이 없어서 테스트코드 생략

### 테스트
- [x] 테스트 코드
- [x] api 테스트

### 관련 이슈(옵셔널)
- 없음

2023-11-02 18:56 UTC, madst0614 approved these changes
필드가 많아서 힘드셨을거 같습니다! 깔끔하게 잘 적어주셨네요. 수고하셨습니다!

2023-11-03 09:49 UTC, HyunsooZo requested changes
전체적으로 깔끔하고 가독성이 좋은것 같습니다.
다만 테스트코드작성으로 일부 로직에 대한 검증이필요할 것 같습니다.
예: `RestaurantService`의 `getDetail()`, `searchList()` 가 레포지토리에서 직접 DTO를 정말 반환하는지 등

2023-11-03 09:49 UTC, HyunsooZo commented on src/main/java/wanted/n/controller/RestaurantController.java
> +}
`RESTful` 원칙을 따르는 API를 구축할 때는 `ResponseEntity<?>`응답값 사용이 
`HTTP` 상태와 응답 데이터의 규범적인 처리에유리하다고 알고있습니다. 
현재 구현된 api는 응답 값만 노출하고 있으므로 상태값 등에대한 처리가 조금필요할것 같아요
참고부탁드립니다~

2023-11-03 09:49 UTC, HyunsooZo commented on src/main/java/wanted/n/service/RestaurantService.java
>      }
해당부분은 `Repository`에서 직접 `DTO`로 반환하는걸까요?
매퍼 패턴에따르면 데이터 액세스 계층(`repository`)에서 엔티티(`entity`)를 반환하고 
서비스 레이어에서 로직처리하여 데이터 전송 객체(`DTO`)로 변환하는 것이 일반적으로 더 정확한 접근 방식이라고 알고있습니다.

해당부분은 레포지토리에 별도 메서드 로직처리가 되어있지않은걸로봐서 예외가 떨어질것 같은데 
테스트코드를 통한 로직체크가 필요해보입니다. 참고부탁드려요~

2023-11-03 10:03 UTC, HyunsooZo approved these changes

2023-11-03 10:15 UTC, 12hyeon approved these changes
참고만 해주세요.
맛집 소개와 관련된 필드가 매우 많은데, 과연 해당 모든 정보가 사용자에게 보여지는 게 좋을지 의문입니다. 고용된 직원 수 같이 필요하지 않은 정보 일부를 resposne에서 제거 하는 것도 하나의 방법이 될 것 같습니다.

2023-11-03 10:24 UTC, merged

2023-11-03 10:24 UTC, junkyu92 commented
> 참고만 해주세요. 맛집 소개와 관련된 필드가 매우 많은데, 과연 해당 모든 정보가 사용자에게 보여지는 게 좋을지 의문입니다. 고용된 직원 수 같이 필요하지 않은 정보 일부를 resposne에서 제거 하는 것도 하나의 방법이 될 것 같습니다.

과제 요구사항입니다!
### 맛집 상세정보(API)

- `맛집 모든필드` 를 포함합니다.

2023-11-03 10:28 UTC, junkyu92 commented on src/main/java/wanted/n/service/RestaurantService.java
>      }
서비스에서 수행되는 로직이 없어서 테스트코드 작성이 무의미한 것 같습니다. 
api 호출 테스트는 완료했습니다.