feat: 리뷰 등록 api 추가
7th-wanted-pre-onboarding-teamN/tasty-spots-finder pull request #8
Opened 2023-11-01 13:40 UTC by junkyu92

### 작업 내용
- 리뷰 등록 api 추가

### 변경 사항(추가시엔 추가사항)
- 리뷰 등록 api 호출시 리뷰 등록 + restaurant 평점, 리뷰 수 업데이트
- Restaurant Entity rate, reviewCount컬럼에 default값 추가
- Restaurant Entity updateReview 메서드 추가
- User Entity reviewList필드 추가

### 특이 사항
- 없음

### 테스트
- [x] 테스트 코드
- [x] api 테스트

### 관련 이슈(옵셔널)
- 없음

2023-11-01 13:50 UTC, HyunsooZo requested changes
전체적으로 깔끔하고 가독성이 좋고
컨벤션도 매우 엄격히 잘 지켜주신것 같습니다. 

다만 `Restaurant` 클래스 파일이 기존 커밋내용에 덮어씌워진것 같습니다! 
해당부분만 수정 해주셨으면 좋겠습니다!

2023-11-01 13:50 UTC, HyunsooZo commented on src/main/java/wanted/n/domain/Restaurant.java
해당 클래스는 제가 이전에 커밋한내용에 덮어씌워진 것 같아요. 
해당부분은 이 코드에 필요하신 메서드 추가하셔서 다시 수정 부탁드릴게요! 

```java
package wanted.n.domain;

import com.fasterxml.jackson.databind.JsonNode;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.DynamicUpdate;

import javax.persistence.Entity;
import javax.persistence.Id;

@Getter
@AllArgsConstructor
@NoArgsConstructor
@Entity
@DynamicUpdate
@Builder
public class Restaurant {
    @Id
    private String id;

    private String sigunName;

    private String sigunCode;

    private String bizPlaceName;

    private String licenseDate;

    private String businessState;

    private String closeDate;

    private String locationPlaceArea;

    private String graduatedFacilityDivision;

    private Integer maleEmployeeCount;

    private String year;

    private String multiUseBusinessEstablishment;

    private String graduatedDivision;

    private String totalFacilityScale;

    private Integer femaleEmployeeCount;

    private String businessSiteCircumferenceDivision;

    private String sanitationIndustryType;

    private String sanitationBusinessCondition;

    private Integer totalEmployeeCount;

    private String refinedRoadNameAddress;

    private String refinedLotNumberAddress;

    private String refinedZipCode;

    private Double refinedLatitude;

    private Double refinedLongitude;

    private Double rate;

    private Long reviewedCount;

    public void updateRestaurant(JsonNode row) {
        this.sigunName = row.get("SIGUN_NM").asText();
        this.sigunCode = row.get("SIGUN_CD").asText();
        this.bizPlaceName = row.get("BIZPLC_NM").asText();
        this.refinedRoadNameAddress = row.get("REFINE_ROADNM_ADDR").asText();
        this.refinedLotNumberAddress = row.get("REFINE_LOTNO_ADDR").asText();
        this.refinedZipCode = row.get("REFINE_ZIP_CD").asText();
        this.refinedLatitude = row.get("REFINE_WGS84_LAT").asDouble();
        this.refinedLongitude = row.get("REFINE_WGS84_LOGT").asDouble();
    }
}

```

2023-11-01 14:31 UTC, madst0614 commented on src/main/java/wanted/n/controller/ReviewController.java
> +    public ResponseEntity<Void> restaurantList(@Valid @RequestBody ReviewRequestDTO reviewRequestDTO
registerReview 혹은 createReview가 더 나을 것 같습니다!

2023-11-01 14:31 UTC, HyunsooZo approved these changes

2023-11-02 04:53 UTC, madst0614 approved these changes

2023-11-02 10:25 UTC, 12hyeon approved these changes

2023-11-02 10:31 UTC, merged